it('github test', function() {
  cy.visit('https://github.com')
  cy.wait(2000)
  cy.get('div.d-flex.flex-justify-between > .d-flex > .js-details-target > .octicon').click()
  cy.wait(2000)
  cy.get('.mr-3 > .HeaderMenu-link').click()
  cy.wait(2000)
  cy.get('#login_field').type('danielslad@gmail.com')
  cy.wait(2000)
  cy.get('#password').type('Daniel1987##')
  cy.wait(2000)
  cy.get('.btn').click()
  cy.wait(2000)
  cy.get('.mr-0.d-none > .details-overlay > .Header-link').click()
  cy.wait(2000)
  cy.get('[href="/Daniel1987Daniel?tab=repositories"]').click()
  cy.wait(2000)
  cy.get(':nth-child(1) > .col-10 > .d-inline-block > .wb-break-all > a').click()
  cy.wait(2000)
  cy.get('.css-truncate > .js-navigation-open').click()
})
